name: Secrets Test

on: push

jobs:
  secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Show secret (safe)
        run: echo "Secret length is ${#API_KEY}"
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - name: Try to print secret (GitHub will mask it)
        run: echo "${{ secrets.API_KEY }}"
